all:
  children:
    frontend:
      hosts:
        vm-frontend:
          ansible_host: 20.13.160.191
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/burgerbuilder
    backend:
      hosts:
        vm-backend:
          ansible_host: 20.13.155.82
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/burgerbuilder